# Generated by Django 3.1.7 on 2021-05-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora_cheque_emitido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('nombre_cajero', models.TextField(default=0)),
                ('id_user', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_cheque_fallido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fallo', models.DateTimeField(auto_now_add=True)),
                ('cuasa', models.TextField(default=0)),
                ('id_cheque', models.PositiveIntegerField(default=0)),
                ('id_user', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_cheque_generado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(default=0)),
                ('lugar_emision', models.TextField(default=0)),
                ('num_cheque', models.PositiveIntegerField(default=0)),
                ('num_cuenta', models.CharField(max_length=10)),
                ('num_chequera', models.PositiveIntegerField(default=0)),
                ('id_cheque', models.PositiveIntegerField(default=0)),
                ('beneficiario', models.TextField(default=0)),
                ('id_user', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_cheque_liberado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liberacion', models.DateTimeField(auto_now_add=True)),
                ('id_grupo', models.PositiveIntegerField(default=0)),
                ('id_user', models.PositiveIntegerField(default=0)),
                ('id_cheque', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_cheque_modificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('monto_antes', models.FloatField(default=0)),
                ('monto_post', models.FloatField(default=0)),
                ('beneficiario_antes', models.TextField(default=0)),
                ('beneficiario_post', models.TextField(default=0)),
                ('id_user', models.PositiveIntegerField(default=0)),
                ('id_cheque', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(max_length=10)),
                ('nombre_banco', models.TextField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('fondo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deposito', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(default=0)),
                ('num_cuenta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(default=0)),
                ('nombre', models.TextField(default=0)),
                ('apellido', models.TextField(default=0)),
                ('dpi', models.CharField(max_length=13)),
                ('direccion', models.TextField(default=0)),
                ('id_rol', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta_bancaria',
            fields=[
                ('num_cuenta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_banco', models.TextField(default=0)),
                ('nombre_cuenta', models.TextField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fondo', models.FloatField(default=0)),
                ('estado', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default=0)),
                ('monto_minimo', models.FloatField(default=0)),
                ('manto_maximo', models.FloatField(default=0)),
                ('nivel_autoridad', models.PositiveIntegerField(default=0)),
                ('generar_cheque', models.PositiveIntegerField(default=0)),
                ('llamar_jefe_departamento', models.PositiveIntegerField(default=0)),
                ('validar_cheque', models.PositiveIntegerField(default=0)),
                ('llamar_jefe_pagos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_superior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crud_users', models.PositiveIntegerField(default=0)),
                ('imprimir_cheque', models.PositiveIntegerField(default=0)),
                ('anular_cheque', models.PositiveIntegerField(default=0)),
                ('modificar_cheque', models.PositiveIntegerField(default=0)),
                ('reporte_cheques', models.PositiveIntegerField(default=0)),
                ('auditar_usuarios', models.PositiveIntegerField(default=0)),
                ('administrar_cuentas_bancarias', models.PositiveIntegerField(default=0)),
                ('auditar_cuenta', models.PositiveIntegerField(default=0)),
                ('mostrar_bitacora_usuario', models.PositiveIntegerField(default=0)),
                ('mostrar_bitacora_grupo', models.PositiveIntegerField(default=0)),
                ('mostrar_bitacura_jefe', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_empresa', models.TextField(default=0)),
                ('representante_nombre', models.TextField(default=0)),
                ('representante_apellido', models.TextField(default=0)),
                ('direccion', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default=0)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.grupo')),
                ('id_permiso_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.permiso_superior')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default=0)),
                ('apellido', models.TextField(default=0)),
                ('dpi', models.CharField(max_length=13)),
                ('direccion', models.TextField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('compania', models.TextField(default=0)),
                ('pais', models.TextField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('compania', models.TextField(default=0)),
                ('pais', models.TextField(default=0)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Correo_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Correo_prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField(default=0)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Chequera',
            fields=[
                ('num_chequera', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('num_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cuenta_bancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cheque', models.CharField(max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(default=0)),
                ('lugar_emision', models.TextField(default=0)),
                ('estado', models.TextField(default=0)),
                ('beneficiario', models.TextField(default=0)),
                ('num_cuenta', models.CharField(max_length=10)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
                ('num_chequera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.chequera')),
            ],
        ),
        migrations.CreateModel(
            name='Buffer_cheque_pendiente_autorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendido', models.PositiveIntegerField(default=0)),
                ('id_cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cheque')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Buffer_cheque_disponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendido', models.PositiveIntegerField(default=0)),
                ('id_cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cheque')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_movimiento_cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bitacora_cheque_emitido')),
                ('no_deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bitacora_deposito')),
            ],
        ),
        migrations.AddField(
            model_name='bitacora_cheque_emitido',
            name='id_cheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cheque'),
        ),
        migrations.CreateModel(
            name='Bitacora_cheque_eliminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.CharField(max_length=3)),
                ('id_cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cheque')),
            ],
        ),
    ]
